# Generated by Django 4.2.7 on 2025-05-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_updates'),
        ('contracts', '0002_initial'),
    ]

    operations = [
    ]
