# Generated by Django 4.2.7 on 2025-05-27 13:47

import contracts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_merge_0002_contract_updates_0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='parties',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='additive_term',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.contract_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='termo aditivo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_document',
            field=models.FileField(upload_to=contracts.models.contract_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fiscal_portaria',
            field=models.FileField(upload_to=contracts.models.contract_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='portaria do fiscal'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, help_text='Título do contrato (obsoleto, usar campo empresa)', max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor total'),
        ),
    ]
