# Generated by Django 4.2.7 on 2025-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Número do contrato no formato CTR-YYYY-NNN', max_length=20, unique=True, verbose_name='número do contrato'),
        ),
    ]
